config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "home#index"
  get 'home/index'
  get '/' => 'home#index'
  
  resources :places 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/addpassword.rb
class Addpassword < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
   has_one :service, dependent: :destroy
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :place
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @places = Place.all   
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  before_action :authenticate_user!
  
  def index
    @place = Place.all 
  end

  def new
  end

  def create
    @place = Place.new(place_params)
    if @place.valid?
      @place.save
    else
      render action: 'new'
    end
    redirect_to places_path
  end 

  def show
    @place = Place.find(params[:id])
  end 

  def place_params
    params.require(:place).permit(:name, :city, :street, :bldg, :description, :tags)
  end


end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/home/index.html.erb
<div align=center>
<h1>Places</h1>
<p><i>of Black Gold</i></p>
</div>
 
<div class="grid">
	<figure class="effect-zoe">
		<div id="map"></div>
		<figcaption>
			<h2>Choose your <span>Coffee place</span></h2>
			<p class="description">Mark restraunt, cafe or whatever bar to order takeaway coffee cup!</p> 
			</figcaption>			
	</figure>				
</div>


<script>
  function initMap() {
    var coord = {lat: 53.9005, lng: 27.559};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: coord
    });
    var marker = new google.maps.Marker({
      position: coord,
      map: map
    });
  }
</script>
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyClE56ThQPOKZ9t3lQejb60T3KFt2U5yII&callback=initMap">
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Places</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <style>
       #map {
        height: 400px;
        width: 100%;
       }
    </style>

    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">       
    <link rel="stylesheet" type="text/css" href="set1.css" />
  </head>

  <body>
  	<header><div id="header-links">
  	<%= link_to 'Home', home_index_path %> | <%= link_to 'Places', places_path %> | <%= link_to 'Register place', new_place_path %> 
    </div>
  	</header>
    <p class="notice"><%=notice%></p>
    <p class="alert"><%=alert%></p>
    <%= yield %>

  </body>
</html>

app/views/places/_form.html.erb
<%= form_for @place, places_path do |f| %>
	<p> 
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p> 
		<%= f.label :password %>
		<%= f.text_field :password %>
	</p>
	<p> 
		<%= f.label :address %>
		<%= f.text_field :city %>
		<%= f.text_field :street %>
		<%= f.text_field :bldg %>
	</p>

	<p> 
		<%= f.label :description %>
		<%= f.text_area :description %>
	</p>

	<p> 
		<%= f.label :tags %>
		<%= f.text_field :tags %>
	</p>
	<p>
		<%= f.submit 'Register', :class => 'button' %>
	</p>
	
<% end %>

app/views/places/edit.html.erb
<h2>Edit you place</h2>

<%= form_for :place,  do |f| %>
	<p> 
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<!-- <p> 
		<%= f.label :password %>
		<%= f.text_field :password %>
	</p> -->
	<p> 
		<%= f.label :address %>
		<%= f.text_field :city %>
		<%= f.text_field :street %>
		<%= f.text_field :bldg %>
	</p>

	<p> 
		<%= f.label :description %>
		<%= f.text_area :description %>
	</p>

	<p> 
		<%= f.label :tags %>
		<%= f.text_field :tags %>
	</p>
	<p>
		<%= f.submit 'Register', :class => 'button' %>
	</p>
	
<% end %>

app/views/places/index.html.erb
<%@place.each do |p|%>

	<table class="place-table">

		<tr>
			<td>
				<h2><%=p.name%></h2>
			</td>
		</tr>

		<tr>
			<td>
				<i><%= p.city %>, <%= p.street %>, <%= p.bldg %></i>
			</td>
		</tr>

		<tr>
			<td>
				<p><%= p.description %></p><h6><%= p.tags %></h6>
			</td>
		</tr>

		<tr>
			<td>
				<%= link_to place_path(p) do %>
					<button type="button" class='button'>View the place</button>
				<%end%>
			</td>
		</tr>

	</table>

<%end%>

app/views/places/new.html.erb
<h2>Register you place</h2>

app/views/places/show.html.erb
<table>
	<tr>
		<td>
			<h2><%= @place.name %></h2>
		</td>
	</tr>
	<tr>
		<td>
		<i><%= @place.city%>, <%= @place.street %>, <%= @place.bldg %></i>
		</td>
	</tr>
	<tr>
		<td>
			<p><%= @place.description %></p><h6><%= @place.tags %></h6>
		</td>
	</tr>
	<tr>
		<td>
			<%= link_to 'edit', edit_place_path %>
		</td>
	</tr>
</table>